# 01_serviceaccount.yml
# ----------------------------------------------------------------------------
# Create a service account for Tiller in tenant's system namespace
# ----------------------------------------------------------------------------
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: sys-tiller
  labels:
    app.kubernetes.io/name: tiller
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: cloudtrain
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: admin-plane
    app.kubernetes.io/stage: devops
