# 02_rbac_ns_fwp-sys-tiller.yml
# ----------------------------------------------------------------------------
# Allows Tiller service account to deploy to tenant's system namespace
# ----------------------------------------------------------------------------
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-to-namespace
  labels:
    app.kubernetes.io/name: deploy-to-namespace
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: hmfwpcnj
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: admin-plane
    app.kubernetes.io/stage: devops
  namespace: fwp-sys-tiller
rules:
  - apiGroups: ["", "batch", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller-deploy-to-namespace
  namespace: fwp-sys-tiller
  labels:
    app.kubernetes.io/name: tiller-deploy-to-namespace
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: hmfwpcnj
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: admin-plane
    app.kubernetes.io/stage: devops
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: fwp-sys-tiller
roleRef:
  kind: ClusterRole
  name: deploy-to-namespace
  apiGroup: rbac.authorization.k8s.io