---
apiVersion: v1
kind: Namespace
metadata:
  name: sys-tiller
  labels:
    app.kubernetes.io/name: sys-tiller
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: cloudtrain
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: admin-plane
    app.kubernetes.io/stage: devops
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: sys-tiller
  name: default-deny-inbound
  labels:
    app.kubernetes.io/name: default-deny-all
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: cloudtrain
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: admin-plane
    app.kubernetes.io/stage: devops
spec:
  podSelector: {}
  policyTypes:
    - Ingress
