---
apiVersion: v1
kind: Namespace
metadata:
  name: int
  labels:
    app.kubernetes.io/name: int
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: cloudtrain
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: tenant
    app.kubernetes.io/stage: integration-test
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: int
  name: default-deny-inbound
  labels:
    app.kubernetes.io/name: default-deny-all
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: cloudtrain
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: tenant
    app.kubernetes.io/stage: integration-test
spec:
  podSelector: {}
  policyTypes:
    - Ingress
