---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    app.kubernetes.io/name: prod
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: cloudtrain
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: tenant
    app.kubernetes.io/stage: production
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: prod
  name: default-deny-inbound
  labels:
    app.kubernetes.io/name: default-deny-all
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: cloudtrain
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: tenant
    app.kubernetes.io/stage: production
spec:
  podSelector: {}
  policyTypes:
    - Ingress
